#!/bin/bash

mkdir -p /home/developer
mkdir /home/developer/tools
echo "developer:x:1000:1000:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd
echo "developer:x:1000:" >> /etc/group
chown developer:developer -R /home/developer
