#!/bin/bash

cd /tmp/setups/squirrel/
wget https://ufpr.dl.sourceforge.net/project/squirrel-sql/1-stable/3.8.1/squirrel-sql-3.8.1-standard.jar
java -jar /tmp/setups/squirrel/squirrel-sql-3.8.1-standard.jar /tmp/setups/squirrel/config