#!/bin/bash

cp /tmp/setups/intellij/ideaU/server /home/developer/tools/ideaU_license_server
cp /tmp/setups/intellij/ideaU/run /home/developer/ideaU
cat /tmp/setups/intellij/ideaU/ideaIU-2017.3.3-no-jdk.tar.gz.* > /tmp/setups/intellij/ideaU/ideaIU-2017.3.3-no-jdk.tar.gz
tar -xzf /tmp/setups/intellij/ideaU/ideaIU-2017.3.3-no-jdk.tar.gz -C /home/developer/tools/
chmod +x /home/developer/tools/idea-IU-173.4301.25/bin/idea.sh
chmod +x /home/developer/ideaU
chmod +x /home/developer/tools/ideaU_license_server
apt-get install libgtk-3-0 libxext6 libxss1 libxext-dev libxrender-dev libxtst-dev -y
