#!/bin/bash

cd /tmp/setups/intellij/ideaC
wget https://download-cf.jetbrains.com/idea/ideaIC-2018.2.4.tar.gz
tar -xzf /tmp/setups/intellij/ideaC/ideaIC-2018.2.4.tar.gz -C /home/developer/tools/
chmod +x /home/developer/tools/idea-IC-182.4505.22/bin/idea.sh
ln -s /home/developer/tools/idea-IC-182.4505.22/bin/idea.sh /home/developer/ideaC
chmod +x /home/developer/ideaC
apt-get install libgtk-3-0 libxext6 libxss1 libxext-dev libxrender-dev libxtst-dev -y
